export const ApiRoute = {
  AUTHENTICATE: {
    PREFLIGHT: `/api/auth/preflight`,
    REGISTER: `/api/auth/register`,
    LOGIN: `/api/auth/login`,
    VERIFY_EMAIL: `/api/auth/verify-email`,
    RESEND_VERIFY: `/api/auth/resend-verify`,
    TOKEN_VERIFICATION: `/api/auth/verification`,
  },
  PROFILE: {
    GET_COUNTRY: `/api/pfp/user/country`,
    UPDATE_COUNTRY: `/api/pfp/user/country`,
    UPLOAD_PHOTO: `/api/pfp/user/photo`,
    GET_PHOTO: `/api/pfp/user/photo`,
    VALIDATE_PASSWORD: `/api/auth/password/validate`,
    UPDATE_PASSWORD: `/api/auth/password/update`,
    UPDATE_USERNAME: `/api/pfp/user/username`,
  },
  PPHS: {
    GET_PPHS_DATA: `/api/hdb/pphs`,
    UPDATE_PPHS_COORDINATES: `/api/hdb/pphs/update`,
    GET_NEAREST_BUSSTOPS: `/api/hdb/pphs/busstops`,
    GET_NEAREST_MRT_STATIONS: `/api/hdb/pphs/mrt`,
    REFRESH_PPHS_COORDINATES: `/api/hdb/pphs/refresh`,
    GET_COORDINATE_OPTIONS: `/api/hdb/pphs/geocode-options`,
    CLEAR_PPHS_COORDINATES: `/api/hdb/pphs/clear-coordinates`,
  },
  LTA: {
    GET_BUS_SVC_BY_BUSSTOP_CODE: `/api/lta/bus/services`,
  },
  ITINERARY: {
    GET_ALL: `/api/itinerary`,
    RETRIEVE_BY_ID: (sessionId: string | undefined) => `/api/itinerary/${sessionId}`,
    RETRIEVE_BY_SHORT_CODE: (shortCode: string) => `/api/itinerary/v/${shortCode}`,
    CREATE: `/api/itinerary`,
    MODIFY: `/api/itinerary/edit`,
    CHECK_PERMISSION: `/api/itinerary/challenge`,
    ADD_COLLABORATOR: `/api/itinerary/add-collaborator`,
    DELETE: (sessionId: string) => `/api/itinerary/delete/${sessionId}`,
  },
  ADMIN: {
    LIST_USERS: `/api/auth/admin/users`,
    UPDATE_USER_ROLES: (id: number) => `/api/auth/admin/users/${id}/roles`,
  },
  FILE: {
    CREATE_TG: `/api/file/tg`,
    DELETE: `/api/file/delete`,
  },
  TG_IMG: {
    UPLOAD: `/api/img/upload`,
    GET: (shortCode: string) => `/api/img/${shortCode}`,
    ADMIN: {
      LIST: `/api/img/admin/list`,
      ADD: `/api/img/admin/add`,
      REMOVE: `/api/img/admin/remove`,
    },
  },
  DOUYIN: {
    CHECK_LIVE: `/api/douyin/live`,
    RANK_LIST: `/api/douyin/ranklist`,
  },
  SCENIC: {
    GET_ALL: `/api/scenic`,
    GET_CHECKLIST: `/api/scenic/checklist`,
    UPSERT_CHECKLIST: `/api/scenic/checklist`,
  },
  TELEGRAM: {
    LINK_STATUS: `/api/telegram/link-status`,
    LINK_TOKEN: `/api/telegram/link-token`,
    MEDIA_LIST: `/api/telegram/media`,
    MEDIA_BY_ID: (id: string) => `/api/telegram/media/${id}`,
    MEDIA_DOWNLOAD: (id: string) => `/api/telegram/media/${id}/download`,
    MEDIA_DELETE: (id: string) => `/api/telegram/media/${id}/delete`,
    MEDIA_EXPIRE: (id: string) => `/api/telegram/media/${id}/expire`,
    MEDIA_UPLOAD: `/api/telegram/media/upload`,
    MEDIA_PREVIEW: (id: string) => `/api/telegram/media/${id}/preview`,
  },
  MARKETPLACE: {
    TRIAL_KEY:        `/api/llm/trial-key`,
    WALLET:           `/api/llm/wallet`,
    TOPUP:            `/api/llm/wallet/topup`,
    API_KEY:          `/api/llm/api-key`,
    ROTATE_API_KEY:   `/api/llm/api-key/rotate`,
    CHAT:             `/api/llm/chat`,
    TRIAL_CHAT:       `/api/llm/trial/chat`,
    SESSIONS:         `/api/llm/sessions`,
    SESSION_MESSAGES: (sessionId: string) => `/api/llm/sessions/${sessionId}`,
    DELETE_SESSION:   (sessionId: string) => `/api/llm/sessions/${sessionId}/delete`,
    MODELS:           `/api/llm/models`,
    ADMIN_MODELS:     `/api/llm/admin/models`,
    ADMIN_MODEL:      (modelId: string) => `/api/llm/admin/models/${encodeURIComponent(modelId)}`,
    ADMIN_SETTINGS:   `/api/llm/admin/settings`,
  },
  SUGGESTION: {
    ACTIVITIES: (destination: string) => `/api/suggestion/activity?destination=${encodeURIComponent(destination)}`,
    PACKING:    `/api/suggestion/packing`,
    CREATE_ACTIVITY: `/api/suggestion/activity`,
    DELETE_ACTIVITY: (id: number) => `/api/suggestion/activity/${id}`,
    CREATE_PACKING:  `/api/suggestion/packing`,
    DELETE_PACKING:  (id: number) => `/api/suggestion/packing/${id}`,
  },
  SS_BABY: {
    FEEDING:  `/v1/ss/baby/feeding`,
    DIAPER:   `/v1/ss/baby/diaper`,
    API_KEY:  `/api/baby/api-key`,
  },
  IOT: {
    API_KEY: `/api/iot-key/api-key`,
  },
  DATA_GOV_SG: {
    // HDB Resale Flat Prices (Jan 2017 onwards) — update resource ID here if dataset changes
    HDB_RESALE_PRICES: `https://data.gov.sg/api/action/datastore_search`,
    HDB_RESALE_RESOURCE_ID: `d_8b84c4ee58e3cfc0ece0d773c8ca6abc`,
  },
}
