export const ApiRoute = {
  AUTHENTICATE: {
    PREFLIGHT: `/api/auth/preflight`,
    REGISTER: `/api/auth/register`,
    LOGIN: `/api/auth/login`,
    VERIFY_EMAIL: `/api/auth/verify-email`,
    RESEND_VERIFY: `/api/auth/resend-verify`,
    TOKEN_VERIFICATION: `/api/auth/verification`,
  },
  PROFILE: {
    GET_COUNTRY: `/api/pfp/user/country`,
    UPDATE_COUNTRY: `/api/pfp/user/country`,
    UPLOAD_PHOTO: `/api/pfp/user/photo`,
    GET_PHOTO: `/api/pfp/user/photo`,
    VALIDATE_PASSWORD: `/api/auth/password/validate`,
    UPDATE_PASSWORD: `/api/auth/password/update`,
  },
  PPHS: {
    GET_PPHS_DATA: `/api/hdb/pphs`,
    UPDATE_PPHS_COORDINATES: `/api/hdb/pphs/update`,
    GET_NEAREST_BUSSTOPS: `/api/hdb/pphs/busstops`,
    GET_NEAREST_MRT_STATIONS: `/api/hdb/pphs/mrt`,
  },
  LTA: {
    GET_BUS_SVC_BY_BUSSTOP_CODE: `/api/lta/bus/services`,
  },
  ITINERARY: {
    GET_ALL: `/api/itinerary`,
    RETRIEVE_BY_ID: (sessionId: string | undefined) => `/api/itinerary/${sessionId}`,
    RETRIEVE_BY_SHORT_CODE: (shortCode: string) => `/api/itinerary/v/${shortCode}`,
    CREATE: `/api/itinerary`,
    MODIFY: `/api/itinerary/edit`,
    CHECK_PERMISSION: `/api/itinerary/challenge`,
    ADD_COLLABORATOR: `/api/itinerary/add-collaborator`,
    DELETE: (sessionId: string) => `/api/itinerary/delete/${sessionId}`,
  },
  ADMIN: {
    LIST_USERS: `/api/auth/admin/users`,
    UPDATE_USER_ROLES: (id: number) => `/api/auth/admin/users/${id}/roles`,
  },
  FILE: {
    CREATE: `/api/file`,
    DELETE: `/api/file/delete`,
  },
  FEATURE: {
    GET_ALL: `/api/feature`,
    TOGGLE: (key: string) => `/api/feature/${key}/toggle`,
  },
  DOUYIN: {
    CHECK_LIVE: `/api/douyin/live`,
    RANK_LIST: `/api/douyin/ranklist`,
  },
  MEAL: {
    GET_BY_DATE: `/api/meal`,
    GET_RANGE: `/api/meal/range`,
    CREATE: `/api/meal`,
    UPDATE: `/api/meal/update`,
    DELETE: `/api/meal/delete`,
    UPLOAD_PHOTO: `/api/meal/photo`,
    DELETE_PHOTO: `/api/meal/photo/delete`,
  },
  WEDDING: {
    EVENTS_GET_ALL: `/api/wedding/events`,
    EVENTS_CREATE: `/api/wedding/events`,
    EVENTS_UPDATE: `/api/wedding/events/update`,
    EVENTS_DELETE: `/api/wedding/events/delete`,
    GUESTS_GET_ALL: `/api/wedding/guests`,
    GUESTS_CREATE: `/api/wedding/guests`,
    GUESTS_UPDATE: `/api/wedding/guests/update`,
    GUESTS_DELETE: `/api/wedding/guests/delete`,
    TABLES_GET_ALL: `/api/wedding/tables`,
    TABLES_CREATE: `/api/wedding/tables`,
    TABLES_DELETE: `/api/wedding/tables/delete`,
    TABLES_ASSIGN: `/api/wedding/tables/assign`,
  },
  EXPENSE: {
    INIT:               `/api/expense`,
    UPDATE_BALANCE:     `/api/expense/balance`,
    CREATE_TRANSACTION: `/api/expense/transaction`,
    UPDATE_TRANSACTION: `/api/expense/transaction/update`,
    DELETE_TRANSACTION: `/api/expense/transaction/delete`,
    CREATE_CARD:        `/api/expense/card`,
    UPDATE_CARD:        `/api/expense/card/update`,
    DELETE_CARD:        `/api/expense/card/delete`,
  },
  DATA_GOV_SG: {
    // HDB Resale Flat Prices (Jan 2017 onwards) — update resource ID here if dataset changes
    HDB_RESALE_PRICES: `https://data.gov.sg/api/action/datastore_search`,
    HDB_RESALE_RESOURCE_ID: `d_8b84c4ee58e3cfc0ece0d773c8ca6abc`,
  },
}
