export const ApiRoute = {
  AUTHENTICATE: {
    PREFLIGHT: `/auth/preflight`,
    REGISTER: `/auth/register`,
    LOGIN: `/auth/login`,
    VERIFY_EMAIL: `/auth/verify-email`,
    RESEND_VERIFY: `/auth/resend-verify`,
    TOKEN_VERIFICATION: `/auth/verification`,
    LOGOUT: `/auth/logout`,
  },
  PROFILE: {
    GET_COUNTRY: `/pfp/user/country`,
    UPDATE_COUNTRY: `/pfp/user/country`,
    UPLOAD_PHOTO: `/pfp/user/photo`,
    GET_PHOTO: `/pfp/user/photo`,
    VALIDATE_PASSWORD: `/auth/password/validate`,
    UPDATE_PASSWORD: `/auth/password/update`,
    UPDATE_USERNAME: `/pfp/user/username`,
  },
  PPHS: {
    GET_PPHS_DATA: `/hdb/pphs`,
    UPDATE_PPHS_COORDINATES: `/hdb/pphs/update`,
    GET_NEAREST_BUSSTOPS: `/hdb/pphs/busstops`,
    GET_NEAREST_MRT_STATIONS: `/hdb/pphs/mrt`,
    REFRESH_PPHS_COORDINATES: `/hdb/pphs/refresh`,
    GET_COORDINATE_OPTIONS: `/hdb/pphs/geocode-options`,
    CLEAR_PPHS_COORDINATES: `/hdb/pphs/clear-coordinates`,
  },
  LTA: {
    GET_BUS_SVC_BY_BUSSTOP_CODE: `/lta/bus/services`,
    GET_BUS_ARRIVAL_TIMING: `/lta/timing`,
  },
  ITINERARY: {
    GET_ALL: `/itinerary`,
    RETRIEVE_BY_ID: (sessionId: string | undefined) => `/itinerary/${sessionId}`,
    RETRIEVE_BY_SHORT_CODE: (shortCode: string) => `/itinerary/v/${shortCode}`,
    CREATE: `/itinerary`,
    MODIFY: `/itinerary/edit`,
    CHECK_PERMISSION: `/itinerary/challenge`,
    ADD_COLLABORATOR: `/itinerary/add-collaborator`,
    DELETE: (sessionId: string) => `/itinerary/delete/${sessionId}`,
  },
  ADMIN: {
    LIST_USERS: `/auth/admin/users`,
    UPDATE_USER_ROLES: (id: number) => `/auth/admin/users/${id}/roles`,
    SEARCH_REQUEST_LOG: (requestId: string) => `/auth/admin/request-logs/${requestId}`,
    RECENT_REQUEST_LOGS: (limit: number) => `/auth/admin/recent-request-logs?limit=${limit}`,
  },
  TELEGRAM_LOG_SUBSCRIPTION: {
    ADMIN_LIST: `/auth/admin/telegram-log-subscriptions`,
    ADMIN_TOGGLE: (chatId: number, moduleKey: string) =>
      `/auth/admin/telegram-log-subscriptions/${chatId}/${moduleKey}`,
  },
  BUDGET: {
    GET_ALL: `/budget`,
    CREATE: `/budget`,
    RETRIEVE_BY_ID: (sessionId: string) => `/budget/${sessionId}`,
    RENAME: (sessionId: string) => `/budget/edit/${sessionId}`,
    DELETE: (sessionId: string) => `/budget/delete/${sessionId}`,
    CREATE_ITEM: (sessionId: string) => `/budget/${sessionId}/item`,
    UPDATE_ITEM: (sessionId: string, itemId: string) => `/budget/${sessionId}/item/${itemId}`,
    DELETE_ITEM: (sessionId: string, itemId: string) => `/budget/${sessionId}/item/${itemId}/delete`,
    RESTORE_ITEM: (sessionId: string, itemId: string) => `/budget/${sessionId}/item/${itemId}/restore`,
    ADD_COLLABORATOR: (sessionId: string) => `/budget/${sessionId}/collaborator`,
    REMOVE_COLLABORATOR: (sessionId: string, userId: number) => `/budget/${sessionId}/collaborator/${userId}/delete`,
  },
  APPLEPAY: {
    GET_ALL: `/applepay`,
    UPDATE_CATEGORY: (transactionId: string) => `/applepay/${transactionId}/category`,
  },
  FILE: {
    CREATE_TG: `/file/tg`,
    DELETE: `/file/delete`,
  },
  TG_IMG: {
    UPLOAD: `/img/upload`,
    GET: (shortCode: string) => `/img/${shortCode}`,
    ADMIN: {
      LIST: `/img/admin/list`,
      ADD: `/img/admin/add`,
      REMOVE: `/img/admin/remove`,
    },
  },
  SCENIC: {
    GET_ALL: `/api/scenic`,
    GET_CHECKLIST: `/api/scenic/checklist`,
    UPSERT_CHECKLIST: `/api/scenic/checklist`,
  },
  TELEGRAM: {
    LINK_STATUS: `/api/telegram/link-status`,
    LINK_TOKEN: `/api/telegram/link-token`,
    MEDIA_LIST: `/api/telegram/media`,
    MEDIA_BY_ID: (id: string) => `/api/telegram/media/${id}`,
    MEDIA_DOWNLOAD: (id: string) => `/api/telegram/media/${id}/download`,
    MEDIA_DELETE: (id: string) => `/api/telegram/media/${id}/delete`,
    MEDIA_EXPIRE: (id: string) => `/api/telegram/media/${id}/expire`,
    MEDIA_UPLOAD: `/api/telegram/media/upload`,
    MEDIA_PREVIEW: (id: string) => `/api/telegram/media/${id}/preview`,
  },
  MARKETPLACE: {
    TRIAL_KEY:        `/api/llm/trial-key`,
    WALLET:           `/api/llm/wallet`,
    TOPUP:            `/api/llm/wallet/topup`,
    API_KEY:          `/api/llm/api-key`,
    ROTATE_API_KEY:   `/api/llm/api-key/rotate`,
    CHAT:             `/api/llm/chat`,
    TRIAL_CHAT:       `/api/llm/trial/chat`,
    SESSIONS:         `/api/llm/sessions`,
    SESSION_MESSAGES: (sessionId: string) => `/api/llm/sessions/${sessionId}`,
    DELETE_SESSION:   (sessionId: string) => `/api/llm/sessions/${sessionId}/delete`,
    MODELS:           `/api/llm/models`,
  },
  SUGGESTION: {
    PACKING:    `/suggestion/packing`,
    NOTES:      (country: string) => `/suggestion/note?country=${encodeURIComponent(country)}`,
    CREATE_PACKING:  `/suggestion/packing`,
    DELETE_PACKING:  (id: number) => `/suggestion/packing/${id}`,
    CREATE_NOTE:     `/suggestion/note`,
    DELETE_NOTE:     (id: number) => `/suggestion/note/${id}`,
  },
  SS_KEY: {
    API_KEY:  `/ss-key/api-key`,
  },
  IOT: {
    API_KEY: `/iot-key/api-key`,
  },
  GARMIN: {
    TODAY: `/garmin/today`,
    SUMMARY: (days: number) => `/garmin/summary?days=${days}`,
  },
  DATA_GOV_SG: {
    // HDB Resale Flat Prices (Jan 2017 onwards) — update resource ID here if dataset changes
    HDB_RESALE_PRICES: `https://data.gov.sg/api/action/datastore_search`,
    HDB_RESALE_RESOURCE_ID: `d_8b84c4ee58e3cfc0ece0d773c8ca6abc`,
  },
}
